### PR TITLE
Add Continuous Boyce Index evaluation to cvTests()

### PR DESCRIPTION
**Pull request by Doi90**

### CODE REVIEW

**Comment by Doi90** [comment]
@skiptoniam any tips for triggering the tests to start? They seem stuck waiting for pending jobs.

**Comment by skiptoniam** [comment]
@Doi90 weird it's setup to fo RMD checks on pull requests to the main/master branch. I'll double check

**Comment by Doi90** [comment]
Thanks @skiptoniam, whatever you did got them running again.

**Comment by skiptoniam** [comment]
I had to trigger it manually from my end so not sure what is happening there. I'll do some digging today. I've merged your pull request.

**Pull request merged**
